#!/bin/bash
clear
echo -e "\033[0m                        \033[47;30mBANNER 2.0\033[0m"
echo " "
echo -e "\033[0;32m
1] ADICIONAR BANNER
2] EXCLUIR BANNER
3] VOLTAR
4] SAIR"
echo -e "\033[0;32mEscolha uma opcão";read -p ": " opcao
clear
if [ "$opcao" = "1" ]
then
chk=$(cat /etc/ssh/sshd_config |grep Banner )
if echo "$chk" |grep -v "#Banner" |grep Banner > /dev/null 2> /dev/null
then
local=$(echo "$chk" |grep -v "#Banner" |grep Banner |awk '{print $2}')
echo  -e "\033[4;34mDigite sua msg para adicionar ao banner"
read -p ": " banner
echo "$banner" > $local
else
echo "Banner /etc/bannerssh" >> /etc/ssh/sshd_config
service ssh restart > /dev/null 2> /dev/null
service sshd restart > /dev/null 2> /dev/null
fi
fi

if [ "$opcao" = "2" ]
then
read -p "Tem certeza que deseja excluir banner [s/n] : " s
if [ "$s" = "n" ]
then
echo -e "Voltando para MENU..."
sleep 3
CONFVPS
fi
if [ "$s" = "s" ]
then
echo "Excluindo banner..."
rm /etc/bannerssh
sleep 2
echo "Banner excluido com sucesso!"
fi
fi
if [ "$opcao" = "3" ]
then
CONFVPS
fi

if [ "$opcao" = "4" ]
then
echo -e "Saindo..."
sleep 3
exit
fi
