#!/bin/bash
echo -e "\033[0m                       \033[47;30mBANNER 2.0\033[0m"
echo " "
echo -e "
1] Adicionar BANNER
2] Editar BANNER
3] Voltar
4] Sair"
echo -e "Escolha uma opcão";read -p ": " opcao
clear
if [ "$opcao" = "1" ]
then
chk=$(cat /etc/ssh/sshd_config |grep Banner )
if echo "$chk" |grep -v "#Banner" |grep Banner > /dev/null 2> /dev/null
then
local=$(echo "$chk" |grep -v "#Banner" |grep Banner |awk '{print $2}')
echo "Digite sua msg para adicionar ao banner"
read -p ": " banner
echo "$banner" > $local
else
echo "Banner /etc/bannerssh" >> /etc/ssh/sshd_config
service ssh restart > /dev/null 2> /dev/null
service sshd restart > /dev/null 2> /dev/null
banner
fi
fi

if [ "$opcao" = "2" ]
then
banner=$(cat /etc/bannerssh)
echo -e "Deseja editar oque no BANNER? "
read -p ": " -e -i $banner edite
echo "$edite" >/etc/bannerssh
fi

if [ "$opcao" = "3" ]
then
CONFVPS
fi

if [ "$opcao" = "4" ]
then
echo -e "Saindo..."
sleep 3
exit
fi
