#!/bin/bash
# cor
b="\033[1;37m"
v="\033[1;32m"
Ver="\033[1;31m"
if [ $(id -u) -eq 0 ]
then
	clear
else
	if echo $(id) |grep sudo > /dev/null
	then
	clear
	echo "Pqp Tu Nao Eh Usuario root vey,"
    sleep 2
    echo "Pra Virar user root Basta Digitar ( sudo su )"
	fi
fi
clear
teste() {
echo -e " \033[1;37m  CONFVPS 5.3  [By: @GLEMYSSON_OFICIAL]\033[0m"
echo " "
echo -e "\033[1;37mEscolha uma das opçoẽs:    \033[1;37mPara Sair escolha a opcao 0\033[1;33m"
echo -e "                    $b[$v 0 $b] $Ver Sair"
echo ""
echo -e "$b[$v 1 $b]$Ver INSTALAR SQUID       $b[$v 11 $b]$Ver DESISTALAR MODULOS"
echo -e "$b[$v 2 $b]$Ver INSTALAR DROPBEAR    $b[$v 12 $b]$Ver ALTERAR SENHA ROOT"
echo -e "$b[$v 3 $b]$Ver INSTALAR OPENVPN     $b[$v 13 $b]$Ver RENICIAR VPS"
echo -e "$b[$v 4 $b]$Ver GERENCIAR USUARIOS"
echo -e "$b[$v 5 $b]$Ver MONITOR SSH"
echo -e "$b[$v 6 $b]$Ver SPEEDTEST"
echo -e "$b[$v 7 $b]$Ver ADD BANNER"
echo -e "$b[$v 8 $b]$Ver ADDHOST"
echo -e "$b[$v 9 $b]$Ver REMOVER CONFVPS"
echo -e "$b[$v 10 $b]$Ver UPDATE VPS"
echo -e "$b----------------------------------------------------"
echo -e "$Ver"
read -p "Escolha um opcao: " opcao
case $opcao in
1)
squid3-installer
;;
2)
dropbear-installer
;;
3)
echo -e ""$v" Em Breve.."
sleep 3
CONFVPS
;;
4)
users-gen
;;
5)
monitor-ssh
;;
6)
speedtest.py
;;
7)
banner
;;
8)
addhost
;;
9)
unistaller-confvps
;;
0)
exit
;;
10)
vps-update
;;
11)
unistaller-modulos
;;
12)
alterar-senha
;;
13)
reboot-vps
;;
esac
}
teste