#!/bin/bash
# cor
b="\033[1;37m"
v="\033[1;32m"
Ver="\033[1;31m"
if [ $(id -u) -eq 0 ]
then
	clear
else
	if echo $(id) |grep sudo > /dev/null
	then
	clear
	echo "Pqp Tu Nao Eh Usuario root vey,"
    sleep 2
    echo "Pra Virar user root Basta Digitar ( sudo su )"
	fi
fi
clear
IP=(cat /etc/IPMENU)
teste() {
echo -e "$b=====================>>>"$v"CONFVPS 2.0"$b"<<<======================"
echo -e " \033[1;37m      CONFVPS 6.0 ["$Ver"By: @GLEMYSSON_OFICIAL"$b"]\033[0m"
echo -e "                 $v Att: 28/04/2017"
echo -e "\033[1;37mEscolha uma das opçoẽs:    \033[1;37mPara Sair escolha a opcao 0\033[1;33m"
echo -e "\033[1;37mSeu IP ($IP)"
echo -e "                    $b[$v 0 $b] $Ver Sair"
echo ""
echo -e "$b["$v"01$b]$Ver INSTALAR SQUID       $b["$v"11$b]$Ver DESISTALAR MODULOS"
echo -e "$b["$v"02$b]$Ver INSTALAR DROPBEAR    $b["$v"12$b]$Ver ALTERAR SENHA ROOT"
echo -e "$b["$v"03$b]$Ver INSTALAR OPENVPN     $b["$v"13$b]$Ver RENICIAR VPS"
echo -e "$b["$v"04$b]$Ver GERENCIAR USUARIOS   $b["$v"14$b]$Ver ATUALIZAR CONFVPS"
echo -e "$b["$v"05$b]$Ver MONITOR SSH          $b["$v"15$b]$Ver OCULTAR IP DO MENU"
echo -e "$b["$v"06$b]$Ver SPEEDTEST"
echo -e "$b["$v"07$b]$Ver ADD BANNER"
echo -e "$b["$v"08$b]$Ver ADDHOST"
echo -e "$b["$v"09$b]$Ver REMOVER CONFVPS"
echo -e "$b["$v"10$b]$Ver UPDATE VPS"
echo -e "$b===========================>>>""<<<==========================="
echo -e "$Ver"
echo -e "$b["$v"Escolha uma opcao"$b"]";read -p "└─>> "  opcao
case $opcao in
1)
squid3-installer
;;
2)
dropbear-installer
;;
3)
vpn-installer
;;
4)
users-gen
;;
5)
monitor-ssh
;;
6)
speedtest.py
;;
7)
banner
;;
8)
addhost
;;
9)
unistaller-confvps
;;
0)
exit
;;
10)
vps-update
;;
11)
unistaller-modulos
;;
12)
alterar-senha
;;
13)
reboot-vps
;;
14)
update-confvps
;;
15)
if cat /etc/IPMENU | grep OCULTADO; then
echo -e 'IP JA FOI OCULTADO DO MENU'
sleep 0.4
echo -e -n 'DESEJA DESOCULTAR IP s/n:';read n
sleep 0.4
   if [[ "$n" = 'n' ]]; then
   	echo -e 'Saindo...'
   	sleep 0.5
   	exit
  fi
   if [[ "$n" = 's' ]]; then
    echo -e 'IPMENU OCULTAR, OPCAO EM TESTES CASO DE
    FALHA CONTATE O AUTOR DO SCRIPT'
    sleep 0.5
    echo -e ''
    echo -e 'Desocultando ip...'
    ip=$(cat /etc/IP)
    echo "$ip" >/etc/IPMENU
     if cat /etc/IPMENU |grep $ip;then
     	echo -e 'IP DESOCULTADO DO MENU'
     	sleep 1
     	echo -e 'Saindo...'
     	sleep 0.4
     	exit
     else
     	echo -e 'Falha ao desocultar ip...'
     	sleep 0.5
     	echo -e 'saindo...'
     	sleep 0.5
     	exit
     fi
   fi
fi
    echo -e 'IPMENU OCULTAR, OPCAO EM TESTES CASO DE
    FALHA CONTATE O AUTOR DO SCRIPT'
    sleep 0.5
    echo -e ''
    echo -e 'Ocultando ip...'
    echo "OCULTADO" >/etc/IPMENU
     if cat /etc/IPMENU |grep OCULTAD; then
     	echo -e 'IP OCULTADO COM SUCESSO'
     else
     	echo -e 'Flha ao ocultar ip...'
     	sleep 0.5
     	echo -e 'Saindo...'
     	sleep 0.5
     	exit 69
     fi
;;
esac
teste