#!/bin/bash
# cor
vermelhoo="\033[1;31m"
if [ $(id -u) -eq 0 ]
then
	clear
else
	if echo $(id) |grep sudo > /dev/null
	then
	clear
	echo "Voce não é root"
	echo "Seu usuario esta no grupo sudo"
	echo -e "Para virar root execute \033[1;31msudo su\033[0m"
	exit
	else
	clear
	echo -e "Vc nao esta como usuario root, nem com seus direitos (sudo)\nPara virar root execute \033[1;31msu\033[0m e digite sua senha root"
	exit
	fi
fi
clear
echo -e " \033[1;37m  CONFVPS 5.0   [By: @GLEMYSSON_OFICIAL]\033[0m"
echo " "
echo -e "\033[1;37mEscolha uma das opçoẽs:    \033[1;37mPara Sair escolha a opcao 9\033[1;33m"
echo -e "\033[1;33m
\033[1;37m[\033[1;32m 1 \033[1;37m]$vermelhoo CONFIGURAR VPS \033[1;30m\033[1;33m
\033[1;37m[\033[1;32m 2 \033[1;37m]$vermelhoo CRIAR USUARIOS \033[1;30m\033[1;33m
\033[1;37m[\033[1;32m 3 \033[1;37m]$vermelhoo DELETAR USUARIO \033[1;30m\033[1;33m
\033[1;37m[\033[1;32m 4 \033[1;37m]$vermelhoo MONITOR SSH \033[1;30m\033[1;33m
\033[1;37m[\033[1;32m 5 \033[1;37m]$vermelhoo ADDHOST \033[1;30m\033[1;33m
\033[1;37m[\033[1;32m 6 \033[1;37m]$vermelhoo REMOVER CONFVPS 2.0 \033[1;30m\033[1;33m
\033[1;37m[\033[1;32m 7 \033[1;37m]$vermelhoo BANNER \033[1;30m\033[1;33m"
echo -e "\033[1;37m[\033[1;32m 8 \033[1;37m]$vermelhoo SSH TUNNELING \033[1;30m\033[1;33m"
echo -e "\033[1;37m[\033[1;32m 9 \033[1;37m]$vermelhoo SAIR \033[1;30m\033[1;33m"
echo -e ""
echo "Escolha uma opcão";read -p ": " opcao
clear
case $opcao in
 1)
  squid3-installer;;
 2)
  create-user;;
 3)
  user-del;;
 4)
  monitor;;
 5)
  addhost;;
 6)
  read -p "Remover? [s/n]: " -e -i n res
  clear
  if [ "$res" = "s" ]
  then
  echo "Removendo CONFVPS 2.0..."
  rm /bin/CONFVPS
  rm /bin/addhost
  rm /bin/squid3-installer
  rm /bin/create-user
  rm /bin/limite
  rm /bin/monitor
  rm /bin/banner
  rm /bin/user-del
  sleep 1
  echo "CONFVPS Removido Com Sucesso!"
   sleep 2
  echo "Saindo..."
 sleep 2
 exit 1
 fi
 if [ "$res" = "n" ]
then
exit
fi;;
 7)
  banner;;
   8)
 ssh-tunneling-installer;;
 9)
 echo "Saindo...!"
 sleep 2
  exit;;
 *)
  id > /dev/null 2> /dev/null
esac