#!/bin/bash
clear
echo -e "\033[0m                \033[47;30m DROPBEAR INSTALLER\033[0m"
echo " "
echo ""
echo -e "\033[0;34m
\033[1;33m1] \033[0;34mUbuntu \033[1;30m \033[1;33m
\033[1;33m2] \033[0;34mDebian \033[1;30m\033[1;33m"
echo ""
echo "Escolha uma opcao";read -p ": " opcao
clear
if [ "$opcao" = "1" ]
then
echo "Port 22
Protocol 2
KeyRegenerationInterval 3600
ServerKeyBits 1024
SyslogFacility AUTH
LogLevel INFO
LoginGraceTime 120
PermitRootLogin yes
StrictModes yes
RSAAuthentication yes
PubkeyAuthentication yes
IgnoreRhosts yes
RhostsRSAAuthentication no
HostbasedAuthentication no
PermitEmptyPasswords no
ChallengeResponseAuthentication no
PasswordAuthentication yes
X11Forwarding yes
X11DisplayOffset 10
PrintMotd no
PrintLastLog yes
TCPKeepAlive yes
#UseLogin no
AcceptEnv LANG LC_*
Subsystem sftp /usr/lib/openssh/sftp-server
UsePAM yes" > /etc/ssh/sshd_config
dono=$(cat /etc/dono)
so=$(cat -n /etc/issue |grep 1 |cut -d' ' -f6,7,8 |sed 's/1//' |sed 's/	//')
echo -e "\033[1;37m========================================================"
echo -e "\033[1;32mSistema:      \033[1;31m]===>   \033[1;37m$so"
echo " "
echo -e "\033[1;32mPortas SSH:   \033[1;31m]===>   \033[1;37m443"
echo " "
echo -e "\033[1;32mDono da VPS:  \033[1;31m]===>   \033[1;39m$dono"
echo -e "\033[1;37m========================================================"
sleep 3
echo -e "\033[1;37m========================================================"
echo -e "\033[1;37m INSTALANDO PRE REQUISITOS..."
apt-get update -y 1>/dev/null 2>/dev/null
sleep 1
echo -e "\033[1;32m   sucesso..."
sleep 1
echo -e "\033[1;37m INSTALANDO DROPBEAR..."
apt-get install dropbear -y 1>/dev/null 2>/dev/null
sleep 1
echo -e "\033[1;32m   sucesso..."
sleep 1
echo -e "\033[1;37m ALTERANDO DROPBEAR..."
echo "NO_START=0" > /etc/default/dropbear
echo "DROPBEAR_PORT=443" >> /etc/default/dropbear
echo "/bin/false" >>/etc/shells
echo -e "\033[1;32m   sucesso..."
sleep 1
echo -e "\033[1;37m RENICIANDO SERVICOS..."
service ssh restart 1>/dev/null 2>/dev/null 
service dropbear restart 1>/dev/null 2>/dev/null
echo -e "\033[1;32m   sucesso..."
sleep 1
echo -e "\033[1;37m SEU SERVIDOR VPS FOI CONFIGURADO COM SUCESSO..."
echo -e "\033[1;37m========================================================"
fi
if [ "$opcao" = "2" ]
then
echo "Port 22
Protocol 2
KeyRegenerationInterval 3600
ServerKeyBits 1024
SyslogFacility AUTH
LogLevel INFO
LoginGraceTime 120
PermitRootLogin yes
StrictModes yes
RSAAuthentication yes
PubkeyAuthentication yes
IgnoreRhosts yes
RhostsRSAAuthentication no
HostbasedAuthentication no
PermitEmptyPasswords no
ChallengeResponseAuthentication no
PasswordAuthentication yes
X11Forwarding yes
X11DisplayOffset 10
PrintMotd no
PrintLastLog yes
TCPKeepAlive yes
#UseLogin no
AcceptEnv LANG LC_*
Subsystem sftp /usr/lib/openssh/sftp-server
UsePAM yes" > /etc/ssh/sshd_config
dono=$(cat /etc/dono)
so=$(cat -n /etc/issue |grep 1 |cut -d' ' -f6,7,8 |sed 's/1//' |sed 's/	//')
echo -e "\033[1;37m========================================================"
echo -e "\033[1;32mSistema:      \033[1;31m]===>   \033[1;37m$so"
echo " "
echo -e "\033[1;32mPortas SSH:   \033[1;31m]===>   \033[1;37m80 22"
echo " "
echo -e "\033[1;32mDono da VPS:  \033[1;31m]===>   \033[1;39m$dono"
echo -e "\033[1;37m========================================================"
sleep 3
echo -e "\033[1;37m========================================================"
echo -e "\033[1;37m INSTALANDO PRE REQUISITOS..."
apt-get update -y 1>/dev/null 2>/dev/null
sleep 1
echo -e "\033[1;32m   sucesso..."
sleep 1
echo -e "\033[1;37m INSTALANDO DROPBEAR..."
apt-get install dropbear -y 1>/dev/null 2>/dev/null
sleep 1
echo -e "\033[1;32m   sucesso..."
sleep 1
echo -e "\033[1;37m ALTERANDO DROPBEAR..."
echo "NO_START=0" > /etc/default/dropbear
echo "DROPBEAR_PORT=443" >> /etc/default/dropbear
echo "/bin/false" >>/etc/shells
echo -e "\033[1;32m   sucesso..."
sleep 1
echo -e "\033[1;37m RENICIANDO SERVICOS..."
service ssh restart 1>/dev/null 2>/dev/null 
service dropbear restart 1>/dev/null 2>/dev/null
echo -e "\033[1;32m   sucesso..."
sleep 1
echo -e "\033[1;37m SEU SERVIDOR VPS FOI CONFIGURADO COM SUCESSO..."
echo -e "\033[1;37m========================================================"
fi