#!/bin/bash
b="\033[1;37m"
v="\033[1;32m"
Ver="\033[1;31m"
clear
echo "/bin/false" >>/etc/shells
echo -e "\033[0m                \033[47;30m DROPBEAR INSTALLER\033[0m"
echo ""
echo -e "      $b Escolha a porta que voce deseja usar"
echo ""
echo ""
echo -e ""$b"[$v 1 $b]$Ver 443 
$b[$v 2 $b]$Ver 80"
echo -e ""$b
read -p "[1 - 2]: " porta
case $porta in
1)
echo -e ""$b"ALTERANDO SSH"
echo "Port 22
Protocol 2
KeyRegenerationInterval 3600
ServerKeyBits 1024
SyslogFacility AUTH
LogLevel INFO
LoginGraceTime 120
PermitRootLogin yes
StrictModes yes
RSAAuthentication yes
PubkeyAuthentication yes
IgnoreRhosts yes
RhostsRSAAuthentication no
HostbasedAuthentication no
PermitEmptyPasswords no
ChallengeResponseAuthentication no
PasswordAuthentication yes
X11Forwarding yes
X11DisplayOffset 10
PrintMotd no
PrintLastLog yes
TCPKeepAlive yes
#UseLogin no
AcceptEnv LANG LC_*
Subsystem sftp /usr/lib/openssh/sftp-server
UsePAM yes" > /etc/ssh/sshd_config
echo -e "$b    [$v OK $b]"
echo -e ""$b"INSTALANDO DROPBEAR"
apt-get install dropbear -y 1>/dev/null 2>/dev/null
echo -e "$b    [$v OK $b]"
echo -e ""$b"ALTERANDO DROPBEAR"
echo "NO_START=0" > /etc/default/dropbear
echo "DROPBEAR_PORT=443" >> /etc/default/dropbear
echo -e "$b    [$v OK $b]"
echo -e ""$b"RENICIANDOS SERVICOS"
service ssh restart 1>/dev/null 2>/dev/null
service dropbear restart 1>/dev/null 2>/dev/null
echo -e "$b    [$v OK $b]"
echo -e ""
echo -e ""$b"SUCESSO! TUDO TERMINADO"
;;
2)
echo -e "             "$ver$b"======>>>AVISO<<<======"
echo ""
echo -e ""$b"Ao instalar dropbear na porta 80 o squid sera parado\ncaso voce tenha ele instalado"
echo ""
sleep 1
read -p "Deseja continuar? : [ s/n ] " -e -i n sim
if [ "$sim" = "s" ];then
echo ""
fi
if [ "$sim" = "n" ];then
echo -e "VOLTANDO AO MENU..."
sleep 2
CONFVPS
fi
echo -e ""$b"PARANDO SQUID"
service squid3 stop 1>/dev/null 2>/dev/null
service squid stop 1>/dev/null 2>/dev/null
echo -e "$b    [$v OK $b]"
echo -e ""$b"ALTERANDO SSH..."
echo "Port 443
Port 22
Protocol 2
KeyRegenerationInterval 3600
ServerKeyBits 1024
SyslogFacility AUTH
LogLevel INFO
LoginGraceTime 120
PermitRootLogin yes
StrictModes yes
RSAAuthentication yes
PubkeyAuthentication yes
IgnoreRhosts yes
RhostsRSAAuthentication no
HostbasedAuthentication no
PermitEmptyPasswords no
ChallengeResponseAuthentication no
PasswordAuthentication yes
X11Forwarding yes
X11DisplayOffset 10
PrintMotd no
PrintLastLog yes
TCPKeepAlive yes
#UseLogin no
AcceptEnv LANG LC_*
Subsystem sftp /usr/lib/openssh/sftp-server
UsePAM yes" > /etc/ssh/sshd_config
echo -e "$b    [$v OK $b]"
echo -e "INSTALANDO DROPBEAR"
apt-get install dropbear -y 1>/dev/null 2>/dev/null
echo -e "$b    [$v OK $b]"
echo -e "ALTERANDO DROPBEAR"
echo "NO_START=0" > /etc/default/dropbear
echo "DROPBEAR_PORT=80" >> /etc/default/dropbear
echo -e "$b    [$v OK $b]"
echo -e "RENICIANDOS SERVICOS"
service ssh restart 1>/dev/null 2>/dev/null
service dropbear restart 1>/dev/null 2>/dev/null
echo -e "$b    [$v OK $b]"
echo -e ""
echo -e "SUCESSO! TUDO TERMINADO"
exit
;;
esac