#!/bin/bash
#cores
corPadrao="\033[0m"
preto="\033[0;30m"
vermelho="\033[0;31m"
verde="\033[0;32m"
amarelo="\033[0;33m"
azul="\033[0;34m"
purple="\033[0;35m"
cyan="\033[0;36m"
cinzaa="\033[0;37m"
pretoCinza="\033[1;30m"
vermelhoo="\033[1;31m"
verdee="\033[1;32m"
amareloo="\033[1;33m"
azull="\033[4;34m"
rosa="\033[1;35m"
cyann="\033[2;36m"
branco="\033[1;37m"
cyann="\033[2;36m"
# BY: Glemysson
while true; do
 echo -e "\033[1;31m ========================================================\033[0m"
 echo -e " \033[47;30m   Usuario                :                Conexoes     \033[0m"
 echo -e "\033[1;31m ========================================================\033[0m"
        for usur in `awk -F : '$3 > 900 { print $1 }' /etc/passwd |grep -v "nobody" |grep -vi polkitd |grep -vi systemd-[a-z] |grep -vi systemd-[0-9]`; do
	usurnum=$(ps -u $usur |grep sshd |wc -l)
        echo -e "\033[0;32m    $(printf '%-42s%s'   $usur                                                      $usurnum) \033[0m"
        echo -e "\033[1;31m ========================================================\033[0m"
        done
sleep 5.5s
clear
done