#!/bin/bash
clear
echo -e "\033[0;34m
\033[1;33m1] \033[0;34mUbuntu \033[1;30m(Ubuntu 16, Ubuntu 15, Ubuntu 14 e outros derivados) \033[1;33m
\033[1;33m2] \033[0;34mDebian \033[1;30m(Debian 8, Debian 7, e outros derivados) \033[1;33m

\033[1;33m3] \033[0;34mCentOS \033[1;30m(CentOS 7 , CentOS 6, e outros derivados) \033[1;33m
\033[1;33m4] \033[0;34mFedora \033[1;30m(Fedora e outros derivados) \033[1;33m"

echo " "
echo "Escolha uma opcao";read -p": " opcao
clear
if [ "$opcao" = "1" ]
then 
IP=$(cat /etc/IP)
dono=$(cat /etc/dono)
so=$(cat -n /etc/issue |grep 1 |cut -d' ' -f6,7,8 |sed 's/1//' |sed 's/	//')
echo -e "\033[1;37m========================================================"
echo -e "\033[1;32mSistema:      \033[1;31m]====>   \033[1;37m$so"
echo  " "
echo -e "\033[1;32mSeu IP:       \033[1;31m]====>   \033[1;37m$IP"
echo " "
echo -e "\033[1;32mPortas SSH:   \033[1;31m]====>   \033[1;37m443 22"
echo " "
echo -e "\033[1;32mPortas SQUID: \033[1;31m]====>   \033[1;37m8080 80 3128"
echo " "
echo -e "\033[1;32mDono da VPS:  \033[1;31m]====>   \033[1;39m$dono"
echo -e "\033[1;37m========================================================"

echo -e "\033[1;37m========================================================"
echo -e "\033[1;37m INSTALANDO PRÉ REQUISITOS..."
apt-get update -y 1>/dev/null 2>/dev/null
apt-get install squid3 -y 1>/dev/null 2>/dev/null
apt-get install squid -y 1>/dev/null 2>/dev/null
sleep 3
echo -e "\033[1;32m   sucesso..."
echo -e "\033[1;37m ALTERANDO SSH..."
echo "Port 22
Port 443
Protocol 2
KeyRegenerationInterval 3600
ServerKeyBits 1024
SyslogFacility AUTH
LogLevel INFO
LoginGraceTime 120
PermitRootLogin yes
StrictModes yes
RSAAuthentication yes
PubkeyAuthentication yes
IgnoreRhosts yes
RhostsRSAAuthentication no
HostbasedAuthentication no
PermitEmptyPasswords no
ChallengeResponseAuthentication no
PasswordAuthentication yes
X11Forwarding yes
X11DisplayOffset 10
PrintMotd no
PrintLastLog yes
TCPKeepAlive yes
#UseLogin no
AcceptEnv LANG LC_*
Subsystem sftp /usr/lib/openssh/sftp-server
UsePAM yes" > /etc/ssh/sshd_config
sleep 3
echo -e "\033[1;32m   sucesso..."
echo -e "\033[1;37m ALTERANDO SQUID..."
cd /etc/squid*
echo "http_port 80" > squid.conf
echo "http_port 8080" >> squid.conf
echo "http_port 8799" >> squid.conf
echo "http_port 3128" >> squid.conf
echo "visible_hostname CONFVPS" >> squid.conf
echo "acl ip dstdomain $IP" >> squid.conf
echo "acl accept method GET" >> squid.conf
echo "acl accept method POST" >> squid.conf
echo "acl accept method OPTIONS" >> squid.conf
echo "acl accept method CONNECT" >> squid.conf
echo "acl accept method PUT" >> squid.conf
echo "acl HEAD method HEAD" >> squid.conf
echo "http_access allow ip" >> squid.conf
echo "http_access allow accept" >> squid.conf
echo "http_access allow HEAD" >> squid.conf
echo "http_access deny all" >> squid.conf
echo " cache deny all" >> squid.conf
ufw allow 443 1>/dev/null 2>/dev/null
ufw allow 80 1>/dev/null 2>/dev/null
ufw allow 8080 1>/dev/null 2>/dev/null
ufw allow 8799 1>/dev/null 2>/dev/null
ufw allow 3128 1>/dev/null 2>/dev/null
sleep 3
echo -e "\033[1;32m   sucesso..."
echo -e "\033[1;37m RENICIANDO SERVIÇOS...."
service squid3 -k restart 1>/dev/null 2>/dev/null 
service squid -k restart 1>/dev/null 2>/dev/null 
service ssh restart 1>/dev/null 2>/dev/null 
sleep 3
echo -e "\033[1;32m   sucesso..."
echo -e "\033[1;37m SEU SERVIDOR VPS FOI CONFIGURADO COM SUCESSO..."
echo -e "$branco========================================================"
fi

if [ "$opcao" = "2" ]
then 
IP=$(cat /etc/IP)
dono=$(cat /etc/dono)
so=$(cat -n /etc/issue |grep 1 |cut -d' ' -f6,7,8 |sed 's/1//' |sed 's/	//')
echo -e "\033[1;37m========================================================"
echo -e "\033[1;32mSistema:      \033[1;31m]====>   \033[1;37m$so"
echo  " "
echo -e "\033[1;32mSeu IP:       \033[1;31m]====>   \033[1;37m$IP"
echo " "
echo -e "\033[1;32mPortas SSH:   \033[1;31m]====>   \033[1;37m443 22"
echo " "
echo -e "\033[1;32mPortas SQUID: \033[1;31m]====>   \033[1;37m8080 80 3128"
echo " "
echo -e "\033[1;32mDono da VPS:  \033[1;31m]====>   \033[1;39m$dono"
echo -e "\033[1;37m========================================================"

echo -e "\033[1;37m========================================================"
echo -e "\033[1;37m INSTALANDO PRÉ REQUISITOS..."
apt-get update -y 1>/dev/null 2>/dev/null
apt-get install squid3 -y 1>/dev/null 2>/dev/null
apt-get install squid -y 1>/dev/null 2>/dev/null
sleep 3
echo -e "\033[1;32m   sucesso..."
echo -e "\033[1;37m ALTERANDO SSH..."
echo "Port 22
Port 443
Protocol 2
KeyRegenerationInterval 3600
ServerKeyBits 1024
SyslogFacility AUTH
LogLevel INFO
LoginGraceTime 120
PermitRootLogin yes
StrictModes yes
RSAAuthentication yes
PubkeyAuthentication yes
IgnoreRhosts yes
RhostsRSAAuthentication no
HostbasedAuthentication no
PermitEmptyPasswords no
ChallengeResponseAuthentication no
PasswordAuthentication yes
X11Forwarding yes
X11DisplayOffset 10
PrintMotd no
PrintLastLog yes
TCPKeepAlive yes
#UseLogin no
AcceptEnv LANG LC_*
Subsystem sftp /usr/lib/openssh/sftp-server
UsePAM yes" > /etc/ssh/sshd_config
sleep 3
echo -e "\033[1;32m   sucesso..."
echo -e "\033[1;37m ALTERANDO SQUID..."
cd /etc/squid*
echo "http_port 80" > squid.conf
echo "http_port 8080" >> squid.conf
echo "http_port 8799" >> squid.conf
echo "http_port 3128" >> squid.conf
echo "visible_hostname CONFVPS" >> squid.conf
echo "acl ip dstdomain $IP" >> squid.conf
echo "acl accept method GET" >> squid.conf
echo "acl accept method POST" >> squid.conf
echo "acl accept method OPTIONS" >> squid.conf
echo "acl accept method CONNECT" >> squid.conf
echo "acl accept method PUT" >> squid.conf
echo "acl HEAD method HEAD" >> squid.conf
echo "http_access allow ip" >> squid.conf
echo "http_access allow accept" >> squid.conf
echo "http_access allow HEAD" >> squid.conf
echo "http_access deny all" >> squid.conf
echo " cache deny all" >> squid.conf
ufw allow 443 1>/dev/null 2>/dev/null
ufw allow 80 1>/dev/null 2>/dev/null
ufw allow 8080 1>/dev/null 2>/dev/null
ufw allow 8799 1>/dev/null 2>/dev/null
ufw allow 3128 1>/dev/null 2>/dev/null
sleep 3
echo -e "\033[1;32m   sucesso..."
echo -e "\033[1;37m RENICIANDO SERVIÇOS...."
service squid3 -k restart 1>/dev/null 2>/dev/null 
service squid -k restart 1>/dev/null 2>/dev/null 
service ssh restart 1>/dev/null 2>/dev/null 
sleep 3
echo -e "\033[1;32m   sucesso..."
echo -e "\033[1;37m SEU SERVIDOR VPS FOI CONFIGURADO COM SUCESSO..."
echo -e "$branco========================================================"
fi

if [ "$opcao" = "3" ]
then 
IP=$(cat /etc/IP)
dono=$(cat /etc/dono)
so=$(cat -n /etc/issue |grep 1 |cut -d' ' -f6,7,8 |sed 's/1//' |sed 's/	//')
echo -e "\033[1;37m========================================================"
echo -e "\033[1;32mSistema:      \033[1;31m]====>   \033[1;37m$so"
echo  " "
echo -e "\033[1;32mSeu IP:       \033[1;31m]====>   \033[1;37m$IP"
echo " "
echo -e "\033[1;32mPortas SSH:   \033[1;31m]====>   \033[1;37m443 22"
echo " "
echo -e "\033[1;32mPortas SQUID: \033[1;31m]====>   \033[1;37m8080 80 3128"
echo " "
echo -e "\033[1;32mDono da VPS:  \033[1;31m]====>   \033[1;39m$dono"
echo -e "\033[1;37m========================================================"

echo -e "\033[1;37m========================================================"
echo -e "\033[1;37m INSTALANDO PRÉ REQUISITOS..."
yum -y update 1>/dev/null 2>/dev/null
yum -y install squid -y 1>/dev/null 2>/dev/null
sleep 3
echo -e "\033[1;32m   sucesso..."
echo -e "\033[1;37m ALTERANDO SSH..."
echo "Port 22
Port 443
Protocol 2
KeyRegenerationInterval 3600
ServerKeyBits 1024
SyslogFacility AUTH
LogLevel INFO
LoginGraceTime 120
PermitRootLogin yes
StrictModes yes
RSAAuthentication yes
PubkeyAuthentication yes
IgnoreRhosts yes
RhostsRSAAuthentication no
HostbasedAuthentication no
PermitEmptyPasswords no
ChallengeResponseAuthentication no
PasswordAuthentication yes
X11Forwarding yes
X11DisplayOffset 10
PrintMotd no
PrintLastLog yes
TCPKeepAlive yes
#UseLogin no
AcceptEnv LANG LC_*
Subsystem sftp /usr/lib/openssh/sftp-server
UsePAM yes" > /etc/ssh/sshd_config
sleep 3
echo -e "\033[1;32m   sucesso..."
echo -e "\033[1;37m ALTERANDO SQUID..."
cd /etc/squid*
echo "http_port 80" > squid.conf
echo "http_port 8080" >> squid.conf
echo "http_port 8799" >> squid.conf
echo "http_port 3128" >> squid.conf
echo "visible_hostname CONFVPS" >> squid.conf
echo "acl ip dstdomain $IP" >> squid.conf
echo "acl accept method GET" >> squid.conf
echo "acl accept method POST" >> squid.conf
echo "acl accept method OPTIONS" >> squid.conf
echo "acl accept method CONNECT" >> squid.conf
echo "acl accept method PUT" >> squid.conf
echo "acl HEAD method HEAD" >> squid.conf
echo "http_access allow ip" >> squid.conf
echo "http_access allow accept" >> squid.conf
echo "http_access allow HEAD" >> squid.conf
echo "http_access deny all" >> squid.conf
echo " cache deny all" >> squid.conf
ufw allow 443 1>/dev/null 2>/dev/null
ufw allow 80 1>/dev/null 2>/dev/null
ufw allow 8080 1>/dev/null 2>/dev/null
ufw allow 8799 1>/dev/null 2>/dev/null
ufw allow 3128 1>/dev/null 2>/dev/null
sleep 3
echo -e "\033[1;32m   sucesso..."
echo -e "\033[1;37m RENICIANDO SERVIÇOS...."
service squid start 1>/dev/null 2>/dev/null 
service squid reload 1>/dev/null 2>/dev/null 
service sshd restart 1>/dev/null 2>/dev/null 
sleep 3
echo -e "\033[1;32m   sucesso..."
echo -e "\033[1;37m SEU SERVIDOR VPS FOI CONFIGURADO COM SUCESSO..."
echo -e "$branco========================================================"
fi

if [ "$opcao" = "4" ]
then 
IP=$(cat /etc/IP)
dono=$(cat /etc/dono)
so=$(cat -n /etc/issue |grep 1 |cut -d' ' -f6,7,8 |sed 's/1//' |sed 's/	//')
echo -e "\033[1;37m========================================================"
echo -e "\033[1;32mSistema:      \033[1;31m]====>   \033[1;37m$so"
echo  " "
echo -e "\033[1;32mSeu IP:       \033[1;31m]====>   \033[1;37m$IP"
echo " "
echo -e "\033[1;32mPortas SSH:   \033[1;31m]====>   \033[1;37m443 22"
echo " "
echo -e "\033[1;32mPortas SQUID: \033[1;31m]====>   \033[1;37m8080 80 3128"
echo " "
echo -e "\033[1;32mDono da VPS:  \033[1;31m]====>   \033[1;39m$dono"
echo -e "\033[1;37m========================================================"

echo -e "\033[1;37m========================================================"
echo -e "\033[1;37m INSTALANDO PRÉ REQUISITOS..."
yum -y update 1>/dev/null 2>/dev/null
yum -y install squid -y 1>/dev/null 2>/dev/null
sleep 3
echo -e "\033[1;32m   sucesso..."
echo -e "\033[1;37m ALTERANDO SSH..."
echo "Port 22
Port 443
Protocol 2
KeyRegenerationInterval 3600
ServerKeyBits 1024
SyslogFacility AUTH
LogLevel INFO
LoginGraceTime 120
PermitRootLogin yes
StrictModes yes
RSAAuthentication yes
PubkeyAuthentication yes
IgnoreRhosts yes
RhostsRSAAuthentication no
HostbasedAuthentication no
PermitEmptyPasswords no
ChallengeResponseAuthentication no
PasswordAuthentication yes
X11Forwarding yes
X11DisplayOffset 10
PrintMotd no
PrintLastLog yes
TCPKeepAlive yes
#UseLogin no
AcceptEnv LANG LC_*
Subsystem sftp /usr/lib/openssh/sftp-server
UsePAM yes" > /etc/ssh/sshd_config
sleep 3
echo -e "\033[1;32m   sucesso..."
echo -e "\033[1;37m ALTERANDO SQUID..."
cd /etc/squid*
echo "http_port 80" > squid.conf
echo "http_port 8080" >> squid.conf
echo "http_port 8799" >> squid.conf
echo "http_port 3128" >> squid.conf
echo "visible_hostname CONFVPS" >> squid.conf
echo "acl ip dstdomain $IP" >> squid.conf
echo "acl accept method GET" >> squid.conf
echo "acl accept method POST" >> squid.conf
echo "acl accept method OPTIONS" >> squid.conf
echo "acl accept method CONNECT" >> squid.conf
echo "acl accept method PUT" >> squid.conf
echo "acl HEAD method HEAD" >> squid.conf
echo "http_access allow ip" >> squid.conf
echo "http_access allow accept" >> squid.conf
echo "http_access allow HEAD" >> squid.conf
echo "http_access deny all" >> squid.conf
echo " cache deny all" >> squid.conf
ufw allow 443 1>/dev/null 2>/dev/null
ufw allow 80 1>/dev/null 2>/dev/null
ufw allow 8080 1>/dev/null 2>/dev/null
ufw allow 8799 1>/dev/null 2>/dev/null
ufw allow 3128 1>/dev/null 2>/dev/null
sleep 3
echo -e "\033[1;32m   sucesso..."
echo -e "\033[1;37m RENICIANDO SERVIÇOS...."
service squid start 1>/dev/null 2>/dev/null 
service squid reload 1>/dev/null 2>/dev/null 
service sshd restart 1>/dev/null 2>/dev/null 
sleep 3
echo -e "\033[1;32m   sucesso..."
echo -e "\033[1;37m SEU SERVIDOR VPS FOI CONFIGURADO COM SUCESSO..."
echo -e "$branco========================================================"
fi
