#!/bin/bash
clear
b="\033[1;37m"
v="\033[1;32m"
Ver="\033[1;31m"
if [[ -e /etc/centos-release || -e /etc/redhat-release ]]; then
	OS=centos
fi
if [[ -e /etc/debian_version ]]; then
	OS="debian"
fi
VERSION_ID=$(cat /etc/os-release | grep "VERSION_ID")
IP=$(cat /etc/IP)
so=$(cat -n /etc/issue |grep 1 |cut -d' ' -f6,7,8 |sed 's/1//' |sed 's/	//')
PORTS="3128 8080 & 80"
SSH="443 & 22"
dono=$(cat /etc/dono)
SIP=$(printf '%-23s' "$IP")
soo=$(printf '%-20s' "$so")
porta=$(printf '%-23s' "$PORTS")
ssh=$(printf '%-23s' "$SSH")
donu=$(printf '%-21s' "$dono")
echo -e "          $b==========>>>"$v"SQUID INSTALLER"$b"<<<=========="
echo ""
echo -e ""$b"--------------------------------------------------------"
echo -e "| $Ver---> "$b"SEU IP: "$Ver"       --->    "$v"$SIP  $b|
| $Ver---> "$b"PORTAS SSH: "$Ver"   --->   "$v" $ssh  $b|
| $Ver---> "$b"PORTAS SQUID: "$Ver" --->   "$v" $porta  $b|
| $Ver---> "$b"SEU NOME: "$Ver"     --->   "$v" $donu    $b|
| $Ver---> "$b"SISTEMA: "$Ver"      --->   "$v" $soo     $b|"
echo -e ""$b"--------------------------------------------------------"
echo ""
echo -e "[[ "$Ver"--> "$b"NSTALANDO PRE REQUISITOS...]]"

		if [[ "$VERSION_ID" = 'VERSION_ID="7"' ]]; then
			apt-get update 1>/dev/null 2>/dev/null
            apt -get install squid3 -y 1>/dev/null 2>/dev/null
		fi
# debian 8
if [[ "$VERSION_ID" = 'VERSION_ID="8"' ]]; then
			apt-get update 1>/dev/null 2>/dev/null
            if apt-get install squid -y 1>/dev/null 2>/dev/null
             then
         echo ""
           else
           apt-get install squid3 -y 1>/dev/null 2>/dev/null
		fi
fi
#Ubuntu 12.04
if [[ "$VERSION_ID" = 'VERSION_ID="12.04"' ]]; then
			apt-get update 1>/dev/null 2>/dev/null
            apt -get install squid3 -y 1>/dev/null 2>/dev/null
		fi
# Ubuntu 14.04
		if [[ "$VERSION_ID" = 'VERSION_ID="14.04"' ]]; then
			apt-get update 1>/dev/null 2>/dev/null
            apt -get install squid3 -y 1>/dev/null 2>/dev/null
		fi
# Ubuntu 16.04
if [[ "$VERSION_ID" = 'VERSION_ID="16.04"' ]]; then
            apt-get update 1>/dev/null 2>/dev/null
            apt -get install squid -y 1>/dev/null 2>/dev/null
fi
# Ubuntu 16.04
if [[ "$VERSION_ID" = 'VERSION_ID="16.10"' ]]; then
            apt-get update 1>/dev/null 2>/dev/null
            apt -get install squid -y 1>/dev/null 2>/dev/null
fi
if [[ "$OS" = 'centos' ]]; then
yum update >/dev/null 2>/dev/null
yum -y install squid >/dev/null 2>/dev/null
fi
echo -e "$b  ["$v"OK$b]  "$v"Sucesso..."
sleep 2

echo -e ""$b"[[ "$Ver"--> "$b"ALTERANDO SSH...]]"
echo "Port 22
Port 443
Protocol 2
KeyRegenerationInterval 3600
ServerKeyBits 1024
SyslogFacility AUTH
LogLevel INFO
LoginGraceTime 120
PermitRootLogin yes
StrictModes yes
RSAAuthentication yes
PubkeyAuthentication yes
IgnoreRhosts yes
RhostsRSAAuthentication no
HostbasedAuthentication no
PermitEmptyPasswords no
ChallengeResponseAuthentication no
PasswordAuthentication yes
X11Forwarding yes
X11DisplayOffset 10
PrintMotd no
PrintLastLog yes
TCPKeepAlive yes
#UseLogin no
AcceptEnv LANG LC_*
Subsystem sftp /usr/lib/openssh/sftp-server
UsePAM yes" > /etc/ssh/sshd_config
sleep 2
echo -e "$b  ["$v"OK$b]  "$v"Sucesso..."

if [[ -d /etc/squid ]]; then
echo -e ""$b"[[ "$Ver"--> "$b"ALTERANDO SQUID...]]"
echo "# Portas do SQUID
http_port 80
http_port 8080
http_port 3128
# ACLs e Liberações
acl accept dstdomain -i $IP
acl allowed dstdomain -i /etc/payloads
acl combr dstdomain -i .com.br
acl com dstdomain -i .com
acl all src 0.0.0.0/0.0.0.0
http_access allow accept
http_access allow allowed
http_access allow combr
http_access allow com
http_access deny all
always_direct allow all
# Anonimo
forwarded_for off
# Pipeline
#pipeline_prefetch on" >/etc/squid/squid.conf
sleep 1
echo -e "$b  ["$v"OK$b]  "$v"Sucesso..."
else
echo -e "'$b"[[ "$Ver"--> "$b"ALTERANDO SQUID3...]]"
echo "# Portas do SQUID
http_port 80
http_port 8080
http_port 3128
# ACLs e Liberações
acl accept dstdomain -i $IP
acl allowed dstdomain -i /etc/payloads
acl combr dstdomain -i .com.br
acl com dstdomain -i .com
acl all src 0.0.0.0/0.0.0.0
http_access allow accept
http_access allow allowed
http_access allow combr
http_access allow com
http_access deny all
always_direct allow all
# Anonimo
forwarded_for off
# Pipeline
#pipeline_prefetch on" >/etc/squid3/squid.conf
sleep 2
echo -e "$b  ["$v"OK$b]  "$v"Sucesso..."
fi
echo -e "$b""[[ "$Ver"--> "$b"RENICIANDO SERVICOS...]]"
if service ssh restart >/dev/null 2>/dev/null; then
service squid restart >/dec/null 2>/dev/null
service squid3 restart >/dev/null 2>/dev/null
else
service sshd restart >/dev/null 2>/dev/null
service squid restart >/dev/null 2>/dev/null
fi
sleep 1
echo -e "$b  ["$v"OK$b]  "$v"Sucesso..."
echo ""
echo -e ""$b"--------------------------------------------------------"
echo -e "SQUID INSTALADO COM SUCESSO, AGORA CRIE UM USUARIO E\nTESTE PRA VER SI ESTAR TUDO OK"
echo -e ""$b"--------------------------------------------------------"