#!/bin/bash
# 
b="\033[1;37m"
v="\033[1;32m"
Ver="\033[1;31m"
user()
{
echo -e " \033[0m            \033[47;30mUsuarios Criados\033[0m"
echo ""
echo -e "$b------------------------------------------"
echo -e "\033[47;30m"$Ver"Usuario C.      Data de E.      Conexoes S\033[0m"
echo -e "$b------------------------------------------"
awk -F : '$3 >= 1000 { print $1 }' /etc/passwd | grep -v "nobody" > /tmp/users.txt
i=0
while read usuario
do
i=$(($i+1))
usurnum=$(ps -u $usuario |grep sshd |wc -l)
data=$(chage -l $usuario |grep -i co |awk -F : '{print $2}')
Dataa=$(printf '%-23s' "$data")
usuariio=$(printf ' %-14s' "$usuario")
cone=$(printf ' %-21s' "$usurnum")
echo -e ""$v"$usuariio $Dataa $cone"
echo -e "$b------------------------------------------"
done < /tmp/users.txt
}
clear
users() 
{
echo -e "\033[1;37m                 \033[47;30mEscolha uma opcao abaixo\033[0m"
echo ""
echo -e "
\033[1;37m[\033[1;32m 1\033[1;37m ] \033[1;31mDeletar Usuario
\033[1;37m[\033[1;32m 2\033[1;37m ] \033[1;31mCriar Usuario
\033[1;37m[\033[1;32m 3\033[1;37m ]\033[1;31m Alterar senha de um usuario
\033[1;37m[\033[1;32m 4\033[1;37m ]\033[1;31m Mudar Data de Expiracao
\033[1;37m[\033[1;32m 5\033[1;37m ]\033[1;31m Mudar Limite de Conexao de um Usuario
\033[1;37m[\033[1;32m 6\033[1;37m ] \033[1;31mVer Usuarios Criados
\033[1;37m[\033[1;32m 7\033[1;37m ] \033[1;31mMenu Principal"
echo ""
echo -e "$b["$v"1"$b"-"$v"7"$b"]";read -p ": " opcao
clear
case $opcao in
1)
read -p "Nome: " name
 pids=$(ps -u $name |awk {'print $1'})
 kill "$pids" >/dev/null 2>/dev/null
 userdel $name 1>/dev/null 2>/dev/null
echo -e "Usuario \033[1;32m$nome\033[1;31m Deletado Com Sucesso!"
;;
2)
clear
read -p "Nome: " name
read -p "Senha: " senha
read -p "Data: " dias
read -p "Limite: " limit
echo -e "\033[0m"
	if cat /etc/passwd |grep $name: |grep -vi [a-z]$name |grep -v [0-9]$name > /dev/null
	then
	echo -e "\033[1;31mUsuario$v $name"$Ver" ja existe\033[0m"
	else
clear
limite $nome $limit
validade=$(date '+%C%y/%m/%d' -d " +$dias days")
validadebr=$(date '+%d/%m/%C%y' -d " +$dias days")
sudo useradd -M -s /bin/false $name -e $validade 1>/dev/null 2>/dev/null
(echo $senha ; echo $senha) | passwd $name 1>/dev/null 2>/dev/null
IP=$(cat /etc/IP)
echo -e "\033[1;32m           Conta Criada com Sucesso"
echo " "
echo -e "\033[1;33mIP:\033[1;37m $IP"
echo -e "\033[1;33mPortas SSH:\033[1;37m 443 e 22"
echo -e "\033[1;33mLogin:\033[1;37m $name"
echo -e "\033[1;33mSenha:\033[1;37m $senha"
echo -e "\033[1;33mProxy:\033[1;37m $IP"
echo -e "\033[1;33mPortas: \033[1;37m 3128 8080 & 80"
echo -e "\033[1;33mValidade:\033[1;37m $validadebr"
echo -e "\033[1;33mLimite de conexoes:\033[1;37m $limit"
fi
;;
3)
read -p "Digite o Nome Do Usuario: " nome
read -p "Digite a Nova Senha: " senha
(echo $senha ; echo $senha) | passwd $nome 1>/dev/null 2>/dev/null
sleep 1
echo -e "Senha do usuario $nome Foi\n Alterada Para $senha"
;;
4)
echo -e "$b"
echo -e "Ex: "$b"Dia: "$v"06
"$b"Mes: "$v"07
"$b"Ano: "$v"2017"
echo ""
echo -e "$b"Faca a Data Como Exemplo acima
echo -e "$v"
read -p "Nome: " nome
if cat /etc/passwd |grep $nome: > /dev/null
then
echo ""
else 
echo ""
echo -e ""$Ver"Usuario $b$nome$Ver Nao existe"
echo ""
exit 
fi
read -p "Digite o dia: " dia
read -p "Digite o mes: " mes
read -p "Digite o ano: " ano
echo ""
if chage -E $dia/$mes/$ano $nome 1>/dev/null 2>/dev/null
then
echo -e ""$b"Nova Data Aplicada Ao Usuario $nome"
echo ""
echo -e "Usuario:$v $nome"
echo -e ""$b"Data de Expiracao:$v $dia/$mes/$ano" 
else
echo -e $Ver Data invalida
sleep 1
echo -e "Por favor Revise Data que voce digitou"
sleep 1
fi
;;
5)
read -p "Digite o Nome Do Usuario: " nome
if cat /etc/passwd |grep $nome: > /dev/null
then
echo ""
else 
echo ""
echo -e ""$Ver"Usuario $b$nome$Ver Nao existe"
echo ""
exit 
fi
read -p "Digite o Novo Limite: " limite
limite $nome $limite
echo -e "Novo Limite Aplicado\n Ao Usuario $nome"
;;
6)
user
;;
7)
CONFVPS
;;
esac
}
users
